services:
  - type: web
    name: proscore-live
    runtime: node
    plan: free # Change if needed
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: PORT
        value: 3000
      - key: GAS_PROXY_URL
        value: https://script.google.com/macros/s/AKfycbymzCMu2r7wO5CAzXAcQjj1xPllg4izS48IZzjBEvXCxRKr4icEOHAvLYT37QuX363JdA/exec
